FROM eclipse-temurin:17

LABEL mentainer="alihaidersw34@gmail.com"

WORKDIR /app

COPY   target/springboot-kafka-consumer-0.0.1-SNAPSHOT.jar /app/springboot-docker-demo.jar

ENTRYPOINT ["java", "-jar", "springboot-docker-demo.jar"]